apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30888
  selector:
    app: nginx
